-- ==============================================================================
-- DATA QUALITY FRAMEWORK: MEDALLION ARCHITECTURE & AUDIT LOGGING
-- Database: DATA_QUALITY_DB | Schema: PUBLIC
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- PHASE 1: ENVIRONMENT & OBJECT INITIALIZATION
-- ------------------------------------------------------------------------------
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS DATA_QUALITY_DB;
USE DATABASE DATA_QUALITY_DB;

CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

-- Central Audit Log Table (JSON Telemetry via VARIANT)
CREATE TABLE IF NOT EXISTS DQ_AUDIT_LOG (
    LOG_ID STRING DEFAULT UUID_STRING(),
    PIPELINE_RUN_ID STRING,
    ENVIRONMENT STRING,
    TARGET_TABLE STRING,
    OVERALL_DQ_SCORE NUMBER(5,2),
    PROMOTION_STATUS STRING, -- 'PROMOTED_WITH_QUARANTINE', 'HALTED'
    CHECKS_DETAIL VARIANT,
    EXECUTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CSV File Format for Ingestion
CREATE OR REPLACE FILE FORMAT KAGGLE_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null', 'NaN')
    EMPTY_FIELD_AS_NULL = TRUE;

-- Internal Snowflake Stage
CREATE OR REPLACE STAGE KAGGLE_STAGE
    FILE_FORMAT = KAGGLE_CSV_FORMAT;

-- ------------------------------------------------------------------------------
-- PHASE 2: MEDALLION ARCHITECTURE TABLES
-- ------------------------------------------------------------------------------

-- 1. BRONZE LAYER: Raw, uncleaned ingestion landing table
CREATE TABLE IF NOT EXISTS BRONZE_KAGGLE_RETAIL (
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    DESCRIPTION STRING,
    QUANTITY INTEGER,
    TRANSACTION_TIMESTAMP VARCHAR, -- Retained as VARCHAR for safe raw COPY INTO
    UNIT_PRICE FLOAT,
    CUSTOMER_ID STRING,
    COUNTRY STRING,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. SILVER LAYER: Cleaned, strongly-typed, curated table
CREATE TABLE IF NOT EXISTS SILVER_KAGGLE_RETAIL (
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    DESCRIPTION STRING,
    QUANTITY INTEGER,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ, -- Strongly typed
    UNIT_PRICE FLOAT,
    CUSTOMER_ID STRING,
    COUNTRY STRING,
    PROMOTED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. QUARANTINE / REJECTS LAYER: Anomaly records failing quality checks
CREATE TABLE IF NOT EXISTS QUARANTINE_KAGGLE_RETAIL (
    QUARANTINE_ID STRING DEFAULT UUID_STRING(),
    PIPELINE_RUN_ID STRING,
    ORDER_ID STRING,
    REJECT_REASON STRING,
    RAW_RECORD VARIANT,
    QUARANTINED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. GOLD LAYER: Business-ready analytical aggregates / Data Mart
CREATE OR REPLACE VIEW GOLD_DAILY_REVENUE_BY_COUNTRY AS
SELECT 
    DATE(TRANSACTION_TIMESTAMP) AS SALES_DATE,
    COUNTRY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(QUANTITY * UNIT_PRICE), 2) AS TOTAL_REVENUE
FROM SILVER_KAGGLE_RETAIL
GROUP BY 1, 2;

-- ------------------------------------------------------------------------------
-- PHASE 3: BRONZE DATA INGESTION
-- Note: Ensure OnlineRetail.csv is uploaded to @KAGGLE_STAGE before running COPY
-- ------------------------------------------------------------------------------

-- Load Raw CSV into Bronze Layer
COPY INTO BRONZE_KAGGLE_RETAIL (
    ORDER_ID, PRODUCT_ID, DESCRIPTION, QUANTITY, 
    TRANSACTION_TIMESTAMP, UNIT_PRICE, CUSTOMER_ID, COUNTRY
)
FROM @KAGGLE_STAGE
FILE_FORMAT = (FORMAT_NAME = 'KAGGLE_CSV_FORMAT')
ON_ERROR = 'CONTINUE';

-- Verify Bronze Load Count
SELECT COUNT(*) AS BRONZE_ROW_COUNT FROM BRONZE_KAGGLE_RETAIL;


-- ==============================================================================
-- PHASE 4: AUDIT VERIFICATION & OBSERVABILITY QUERIES
-- (Execute AFTER running python/run_dq_assessment.py)
-- ==============================================================================

-- 1. Unpack Audit Telemetry & Track Medallion Promotion
SELECT 
    PIPELINE_RUN_ID,
    TARGET_TABLE,
    OVERALL_DQ_SCORE,
    PROMOTION_STATUS,
    CHECKS_DETAIL:scores.completeness_score::FLOAT AS COMPLETENESS_SCORE,
    CHECKS_DETAIL:scores.uniqueness_score::FLOAT AS UNIQUENESS_SCORE,
    CHECKS_DETAIL:scores.validity_score::FLOAT AS VALIDITY_SCORE,
    CHECKS_DETAIL:metrics.total_records::INT AS BRONZE_TOTAL_RECORDS,
    CHECKS_DETAIL:metrics.duplicate_item_records::INT AS DUPLICATE_ITEM_RECORDS,
    CHECKS_DETAIL:metrics.missing_customer_ids::INT AS MISSING_CUSTOMER_IDS,
    CHECKS_DETAIL:metrics.invalid_quantities::INT AS INVALID_QUANTITIES,
    CHECKS_DETAIL:metrics.invalid_unit_prices::INT AS INVALID_UNIT_PRICES,
    EXECUTION_TIMESTAMP
FROM DATA_QUALITY_DB.PUBLIC.DQ_AUDIT_LOG
ORDER BY EXECUTION_TIMESTAMP DESC;

-- 2. Verify Record Distribution Across Medallion Layers
SELECT 'BRONZE' AS LAYER, COUNT(*) AS RECORD_COUNT FROM BRONZE_KAGGLE_RETAIL
UNION ALL
SELECT 'SILVER' AS LAYER, COUNT(*) AS RECORD_COUNT FROM SILVER_KAGGLE_RETAIL
UNION ALL
SELECT 'QUARANTINE' AS LAYER, COUNT(*) AS RECORD_COUNT FROM QUARANTINE_KAGGLE_RETAIL;

-- 3. Query Top Rejection Reasons from Quarantine Layer
SELECT 
    REJECT_REASON, 
    COUNT(*) AS REJECTED_ROW_COUNT
FROM QUARANTINE_KAGGLE_RETAIL
GROUP BY REJECT_REASON
ORDER BY REJECTED_ROW_COUNT DESC;
